celeryDemo/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('demo.urls')),
]

demo/urls.py
from django.urls import path
from . import views

app_name = 'demo'
urlpatterns = [
    path('', views.index, name='index'),
    path('calc/', views.calc, name='calc'),
    path('listenToTask/', views.check_status, name="listenToTask"),
]

demo/views.py
from django.http import JsonResponse
from django.shortcuts import render
from .tasks import double_a_integer

import json
from datetime import datetime, timezone, timedelta
from celery.result import AsyncResult


def index(request):
    return render(request, "index.html")


def calc(request):
    if request.is_ajax() and request.method == "POST":
        data = json.loads(request.body)
        number = int(data["number"])
        # convert to utc+8
        event_time = datetime.strptime(data["eventTime"],
                                       "%a, %d %b %Y %H:%M:%S %Z") \
            .replace(tzinfo=timezone.utc) \
            .astimezone(timezone(timedelta(hours=8)))

        task = double_a_integer.apply_async((number, event_time), countdown=5)
        context = {"task_id": task.task_id}
        return JsonResponse(context)


def check_status(request):
    task_id = request.GET.get("task_id")
    if task_id:
        result = AsyncResult(task_id)
        if result.status == "SUCCESS":
            event_time, processing_time, finish_time, data = result.get(timeout=10)
            res = {
                "task_id": task_id,
                "status": result.status,
                "eventTime": event_time,
                "processingTime": processing_time,
                "finishTime": finish_time,
                "result": data
            }
            return JsonResponse(res)
        else:
            return JsonResponse({"status": result.status})
    else:
        return JsonResponse({"status": "NOT FOUND"})

demo/templates/base.html
<!DOCTYPE html>
<html lang="zh-CN">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="A simple Celery demo">
    <meta name="author" content="voidcounter@gmail.com">
    <title>Celery Demo</title>
    {% load static %}
    <link rel="icon" href="{% static 'img/celery.png' %}">
    <!-- Bootstrap core CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">
        <!-- Custom styles for this template -->
    <link rel="stylesheet" type="text/css" href="{% static 'css/dashboard.css' %}">
</head>

<body>
<div class="container-fluid">
    <nav class="navbar navbar-dark fixed-top bg-dark flex-md-nowrap p-0 shadow">
        <a class="navbar-brand col-sm-3 col-md-2 mr-0" href="#">Celery Demo</a>
    </nav>
    .
    <main role="main" class="col-md-9 ml-sm-auto col-lg-10 px-4">
        {% block content %}
        {% endblock %}
    </main>
</div>

<!-- Pass template url to js, see: https://stackoverflow.com/questions/37311042/call-django-urls-inside-javascript-on-click-event/49824680#49824680-->
<input type="hidden" id="u_calc" data-url="{% url 'demo:calc' %}"/>
<input type="hidden" id="u_check" data-url="{% url 'demo:listenToTask' %}"/>

<!-- Placed at the end of the document so the pages load faster -->
<script src="{% static 'js/jquery-3.4.1.min.js' %}"></script>
<script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
<script src="{% static 'js/index.js' %}"></script>
</body>
</html>

demo/templates/index.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

    <form method="post" action="{% url 'demo:calc' %}">
        {% csrf_token %}
        <label for="single">Input a integer </label>
        <input type="text" name="number" placeholder="32" id="number">
        <button id="b01" type="button" onclick="get_result($('#number'))" class="btn  btn-lg btn-danger "
                style="height:35px;width:100px;font-size:14px">
            OK
        </button>
    </form>
    <table class="table" style="visibility:hidden" id="table">
        <thead>
        <tr>
            <th>task id</th>
            <th>event time</th>
            <th>process time</th>
            <th>finish time</th>
            <th>result</th>
        </tr>
        </thead>
        <tbody>
        </tbody>
    </table>
{% endblock %}